# Generated by Django 3.1.2 on 2020-10-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_planet_user_cnt'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='planet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planets.planet'),
        ),
    ]
