# Generated by Django 3.1.2 on 2020-10-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lastlogined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='report_user_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='report_feed_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questlist',
            name='state',
            field=models.CharField(choices=[('TODO', 'todo'), ('DOING', 'doing'), ('DONE', 'done'), ('ABANDON', 'abandon')], default='TODO', max_length=10),
        ),
    ]
