# Generated by Django 3.1.2 on 2020-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date',
            field=models.DateField(),
        ),
    ]
