# Generated by Django 3.1.2 on 2020-10-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trashcan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('address', models.TextField()),
                ('state', models.CharField(choices=[('C', 'confirmed'), ('NC', 'notConfirmed')], default='NC', max_length=15)),
            ],
        ),
    ]
