# Generated by Django 3.1.2 on 2020-10-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashcans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='delete_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
