# Generated by Django 3.1.2 on 2020-10-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='user_cnt',
            field=models.IntegerField(default=1),
        ),
    ]
