# Generated by Django 3.1.2 on 2020-10-14 02:47

import datetime
from django.db import migrations, models
import planets.models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_planet_user_cnt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='planet',
            name='user_cnt',
        ),
        migrations.AlterField(
            model_name='planet',
            name='end_date',
            field=models.DateField(default=planets.models.cal_end_date),
        ),
        migrations.AlterField(
            model_name='planet',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
